### PR TITLE
fix: silence error when plugin policy dir missing

### LINKED ISSUE #212: Better log message when no plugin policies found
Currently the error message in log makes it sound like something went wrong:

`Error checking policy plugins: failed to load policy commands: policy plugin directory (/etc/opk/policy.d) has insecure permissions: failed to describe the file at path: CreateFile /etc/opk/policy.d: The system cannot find the path specified. `

This isn't really an error. It should say something like

`Skipping policy plugins: no plugins found at  /etc/opk/policy.d`

### PR DESCRIPTION
**Pull request by bmodotdev**
The policy plugin directory, i.e. “/etc/opk/policy.d”, is optional. If the directory is missing, do not print an error, print a more friendly message that conveys the missing directory.

Close #212

### CODE REVIEW

**Comment by bmodotdev** [comment]
I wasn't sure if there is an opinion or pattern around emitting errors in this project. Since errors are being wrapped, with `fmt.Errorf()` and `%w`, we can use `errors.Is()` to pivot upon `os.ErrNotExist` even though it might occur a few functions below.

Should we be more proper and define our own sentinel errors as to not require consumers to expect `os.ErrNotExist`, e.g. `policy/plugins.ErrPolicyDirNotExist`? If so, is there a strong opinion on use of `errors.New()` vs custom error types?

For now, I added a small test just to enforce that we wrap `os.ErrNotExist`. Please let me know if you want a more in-depth fix or at another layer in this stack.

I tested this again using podman and tailing `/var/log/opkssh.log`, looking for the error noted in the linked issue, and the new output below:
> Skipping policy plugins: no plugins found at /etc/opk/policy.d

**Comment by EthanHeilman** [comment]
> I wasn't sure if there is an opinion or pattern around emitting errors in this project.

@bmodotdev There is not but there should be. It is something the project needs and is on my TODO list but probably won't happen for a while unless someone else does it.

> Should we be more proper and define our own sentinel errors as to not require consumers to expect os.ErrNotExist, e.g. policy/plugins.ErrPolicyDirNotExist? If so, is there a strong opinion on use of errors.New() vs custom error types?

I have no strong opinion other than favoring simplicity and effectiveness over consistency. Generally we fail when we hit an error and then log the error so most of the errors.New gets the job done. However there are places where we want to check the error and either fail or continue but warning. Those are good places for custom errors to signal what type of error was thrown.

File: policy/enforcer.go [hunk 1]
```diff
@@ -40,6 +42,9 @@ type checkedClaims struct {
 	Groups []string `json:"groups"`
 }
 
+// The default location for policy polugins
```
Comment (EthanHeilman) [inline policy/enforcer.go]:
```suggestion
// The default location for policy plugins
```

File: policy/enforcer.go [hunk 2]
```diff
@@ -65,9 +70,13 @@ func validateClaim(claims *checkedClaims, user *User) bool {
 func (p *Enforcer) CheckPolicy(principalDesired string, pkt *pktoken.PKToken, userInfoJson string, sshCert string, keyType string) error {
 	pluginPolicy := plugins.NewPolicyPluginEnforcer()
 
-	results, err := pluginPolicy.CheckPolicies("/etc/opk/policy.d", pkt, userInfoJson, principalDesired, sshCert, keyType)
+	results, err := pluginPolicy.CheckPolicies(pluginPolicyDir, pkt, userInfoJson, principalDesired, sshCert, keyType)
 	if err != nil {
-		log.Printf("Error checking policy plugins: %v \n", err)
+		if errors.Is(err, os.ErrNotExist) {
```
Comment (EthanHeilman) [inline policy/enforcer.go:75]: I see you have a test, so I `os.ErrNotExist` is getting thrown and this works, but I'm curious is `afero.ReadDir` throwing `os.ErrNotExist`?

**Review by EthanHeilman — APPROVED** [review]
Thanks for improving the logging!

File: policy/enforcer.go (hunk 2 above)
Comment (bmodotdev) [reply policy/enforcer.go:75]: It's coming from `policy/files.PermsChecker.CheckPerm()` when it calls `afero.Fs.Stat()` https://github.com/openpubkey/opkssh/blob/49f451d5b0307cbe954d4d96720ab14e570ec5bd/policy/files/permschecker.go#L58

I have not used afero before, so I checked it's source code; which it's just a [wrapper](https://github.com/spf13/afero/blob/v1.14.0/os.go#L86) around `os.Stat()`

I believe the stack is:
`policy/enforcer.Enforcer.CheckPolicy()` [calls](https://github.com/openpubkey/opkssh/blob/49f451d5b0307cbe954d4d96720ab14e570ec5bd/policy/enforcer.go#L73)  `policy/plugins.PolicyPluginEnforcer.CheckPolicies()` [calls](https://github.com/openpubkey/opkssh/blob/49f451d5b0307cbe954d4d96720ab14e570ec5bd/policy/plugins/plugins.go#L186C26-L186C37) `policy/plugins.PolicyPluginEnforcer.loadPlugins()` [calls](https://github.com/openpubkey/opkssh/blob/49f451d5b0307cbe954d4d96720ab14e570ec5bd/policy/files/permschecker.go#L58) `policy/files.PermsChecker.CheckPerm()`.
